[env]
  NODE_ENV = "production"
  PORT = "8080"  # Fly will forward traffic to this port

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
